[build]
publish = "public"
command = "npm run tinacms build && hugo"

[context.production.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run tinacms build && hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run tinacms build && hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.108.0"

[context.branch-deploy]
command = "npm run tinacms build && hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.108.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200